## Латиков Александр, вариант 5, задача 8.11.5

Задача - необходимо решить систему уравнений:

x' = -sig(x - y)

y' = -xz + rx - y

z' = xy - bz

Начальные условия: x(0) = y(0) = z(0) = 1

b = 8 / 3, sig = 10, r = 28, 0 <= t <= 50

Для решения задачи используются методы Рунге-Кутты 1-4 порядков

In [3]:
import numpy as np              
import matplotlib.pyplot as plt

In [16]:
bi = 8.0 / 3.0
sig = 10.0
r = 28.0
h = 0.001
t = 50.0
y0 = np.array([1.0, 1.0, 1.0])

def f(y):
    y1 = np.copy(y)
    y1[0] = -sig * (y[0] - y[1])
    y1[1] = (-1) * y[0] * y[2] + r * y[0] - y[1]
    y1[2] = y[0] * y[1] - bi * y[2]
    return y1

In [19]:
def step(yn):
    k = np.arange(b.size * yn.size, dtype = float).reshape(b.size, yn.size)
    for i in range(b.size):
        yi = np.copy(yn)
        for j in range(i):
            yi += h * a[i][j] * k[j] 
        k[i] = f(np.copy(yi))
    y_old = np.copy(yn)
    for i in range(b.size):
        yn += h * b[i] * k[i]
    ##d = 0
    ##for i in range (yn.size):
    ##    d += (yn[i] - y_old[i]) ** 2
    ##print(d)
    return yn

Таблицы Бутчера взяты из учебника за авторством И.Б.Петрова и А.И.Лобанова

In [23]:
##первый порядок аппроксимации
b = np.array([1.0])
c = np.array([0.0])
a = np.array([
        np.array([0.0])
])

In [29]:
##второй порядок аппроксимации
b = np.array([0.0, 1.0])
c = np.array([0.0, 0.5])
a = np.array([
        np.array([0.0, 0.0]),
        np.array([0.5, 0.0])
])

In [31]:
##третий порядок аппроксимации
b = np.array([1.0 / 6.0, 2.0 / 3.0, 1.0 / 6.0])
c = np.array([0.0, 0.5, 1.0])
a = np.array([
        np.array([0.0, 0.0, 0.0]),
        np.array([0.5, 0.0, 0.0]),
        np.array([0.0, 1.0, 0.0])
])

In [33]:
##четвертый порядок аппроксимации
b = np.array([1.0 / 6.0, 1.0 / 3.0, 1.0 / 3.0, 1.0 / 6.0])
c = np.array([0.0, 0.5, 0.5, 1.0])
a = np.array([
        np.array([0.0, 0.0, 0.0, 0.0]),
        np.array([0.5, 0.0, 0.0, 0.0]),
        np.array([0.0, 0.5, 0.0, 0.0]),
        np.array([0.0, 0.0, 1.0, 0.0])
])

In [34]:
y_trace = np.array([np.copy(y0)])
for i in range(round(t / h)):
    y_trace = np.append(y_trace, [step(np.copy(y_trace[i]))], axis = 0)
for i in range(y_trace.size // 3):
    if(i % 100 == 0):
        print(y_trace[i])

[1. 1. 1.]
[2.13310762 4.47142018 1.11389889]
[ 6.54252755 13.73118671  4.18019741]
[16.68481396 27.18349235 26.20646018]
[15.36620011  1.11303753 46.75784334]
[ 1.19827299 -8.86719773 32.45474023]
[-4.83321401 -8.06128111 26.67318955]
[-7.04936183 -8.7474865  24.89008216]
[ -8.6355093  -10.09563918  25.64672605]
[ -9.69220069 -10.15778173  28.03033906]
[-9.37857001 -8.35703379 29.36232533]
[-8.07861859 -6.77019936 28.18342435]
[-7.17339714 -6.78342378 25.97599215]
[-7.36206031 -8.09977411 24.55428241]
[-8.48479326 -9.84967704 25.08112225]
[ -9.67232428 -10.43194463  27.51743363]
[-9.64389509 -8.80862231 29.44101522]
[-8.34628633 -6.87301663 28.67062019]
[-7.19910069 -6.53617872 26.37594711]
[-7.14634299 -7.69458546 24.573314  ]
[-8.17349993 -9.56202368 24.62070205]
[ -9.54096363 -10.62853973  26.90562089]
[-9.87110396 -9.3292964  29.37932605]
[-8.66712917 -7.08277214 29.15916835]
[-7.28919088 -6.33213095 26.86518988]
[-6.9595736  -7.27246924 24.70312218]
[-7.83460909 -9.17965125 24.22

[ 0.11501471 -0.84892459 19.71153934]
[-0.52686679 -1.04284243 15.11840106]
[-1.19084992 -2.12308037 11.69615663]
[-2.70476289 -5.02615721  9.54949602]
[ -6.48620757 -12.11682007  10.70321536]
[-13.86488586 -21.56603721  24.3667746 ]
[-15.1887911   -8.02794343  42.07521938]
[-5.24243083  3.67703612 33.18207979]
[ 0.54432166  3.80279219 24.81465094]
[ 2.77174121  4.55503731 19.66204159]
[ 4.92224051  7.72411396 17.10879954]
[ 8.71701079 13.45034155 19.52075322]
[13.06292614 15.58822881 30.17928124]
[11.4914359   6.2627028  35.91198618]
[ 5.84397482  1.14158214 29.83491912]
[ 2.89491181  1.51623693 23.24838249]
[ 2.58452196  3.17289437 18.32363633]
[ 4.00019353  6.32885599 15.36146471]
[ 7.53892082 12.39259835 16.49041926]
[12.95156698 17.59886043 27.20784769]
[13.10337431  8.12951473 37.66808966]
[ 6.39980811  0.13569236 31.76476404]
[ 2.222187   -0.04312929 24.26066175]
[ 1.12321129  0.87355585 18.63072238]
[ 1.3791974   2.09753298 14.42275226]
[ 2.67624062  4.70711799 11.63164072]
[ 5

[ 5.05229268  0.66670902 28.90074352]
[ 2.43468279  1.30892747 22.383116  ]
[ 2.26601438  2.90127015 17.5431443 ]
[ 3.67168054  5.95256954 14.55130141]
[ 7.18715837 12.10187374 15.41616511]
[12.9339281  18.24380281 26.2258563 ]
[13.62502684  8.67316851 38.32146166]
[ 6.48432596 -0.35848039 32.34169922]
[ 1.88208044 -0.67047887 24.5202093 ]
[ 0.52006073 -0.02777484 18.74698168]
[ 0.32747737  0.38037006 14.3645668 ]
[ 0.54942498  0.95372795 11.02663252]
[1.24936955 2.35261304 8.57114269]
[3.13296541 6.09618931 7.34736173]
[ 8.01416275 15.22493277 10.77112854]
[16.27506171 22.47769727 31.12282683]
[13.01087179  1.52697773 42.18018224]
[ 2.32593936 -5.23544608 30.60840478]
[-2.34223621 -5.04248937 23.66323381]
[-4.56049637 -6.78518081 19.93458269]
[ -7.37668561 -10.89057325  19.90915143]
[-11.15877659 -14.52221601  26.14437004]
[-12.13373961 -10.10172874  33.83049864]
[-8.19323941 -3.62034694 31.78429883]
[-4.73467564 -2.65238891 25.86749214]
[-3.92017915 -4.22895304 21.01272632]
[-5.19870

Результаты решения диффура с шагом h = 0.001 для 1-4 порядка апроксимации выложены в 1-4.txt. Для краткости выведен только каждый 100-ый отсчет.

Устойчивых положений равновесия у уравнения нет, для разных методов можно наблюдать значительное расхождение на дистанции t = 50. Отсутствие положений равновесия и хаотичность решения подтверждается здесь: https://en.wikipedia.org/wiki/Lorenz_system .